"""add_handle_positions

Revision ID: 4f12ccccc42a
Revises: ae5bd4d47dcf
Create Date: 2025-09-27 17:20:42.948711

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4f12ccccc42a'
down_revision = 'ae5bd4d47dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('kb_connection_asset_handle', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('kb_connection_kb_handle', sa.String(), nullable=True))
    op.add_column('collections', sa.Column('kb_connection_asset_handle', sa.String(), nullable=True))
    op.add_column('collections', sa.Column('kb_connection_kb_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'kb_connection_kb_handle')
    op.drop_column('assets', 'kb_connection_asset_handle')
    op.drop_column('collections', 'kb_connection_kb_handle')
    op.drop_column('collections', 'kb_connection_asset_handle')
    # ### end Alembic commands ###
