"""add_knowledge_base_links_to_assets_and_collections

Revision ID: ae5bd4d47dcf
Revises: c2d3d7729e93
Create Date: 2025-09-23 01:24:04.058304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5bd4d47dcf'
down_revision = 'c2d3d7729e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('knowledge_base_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_knowledge_base_id'), 'assets', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    op.add_column('collections', sa.Column('knowledge_base_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_collections_knowledge_base_id'), 'collections', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(None, 'collections', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_knowledge_base_id'), table_name='collections')
    op.drop_column('collections', 'knowledge_base_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_knowledge_base_id'), table_name='assets')
    op.drop_column('assets', 'knowledge_base_id')
    # ### end Alembic commands ###
