"""add starred and archived fields to workspace

Revision ID: c13f8859cc8a
Revises: 6c03c15f27cb
Create Date: 2025-10-04 03:30:32.475453

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c13f8859cc8a'
down_revision = '6c03c15f27cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('is_starred', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'is_archived')
    op.drop_column('workspaces', 'is_starred')
    # ### end Alembic commands ###
