"""add_collections_and_update_assets

Revision ID: c2d3d7729e93
Revises: ad29ab2fbb3f
Create Date: 2025-09-23 00:55:19.607021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2d3d7729e93'
down_revision = 'ad29ab2fbb3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.create_index(op.f('ix_boards_title'), 'boards', ['title'], unique=False)
    op.create_index(op.f('ix_boards_user_id'), 'boards', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_collections_workspace_id'), 'collections', ['workspace_id'], unique=False)
    op.add_column('assets', sa.Column('file_path', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('title', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_collection_id'), 'assets', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_bases_collection_name_key'), 'knowledge_bases', type_='unique')
    op.drop_index(op.f('ix_knowledge_bases_collection_name'), table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_collection_name'), 'knowledge_bases', ['collection_name'], unique=True)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'agent', name='messagerole'),
               nullable=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'agent', name='messagerole'),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_bases_collection_name'), table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_collection_name'), 'knowledge_bases', ['collection_name'], unique=False)
    op.create_unique_constraint(op.f('knowledge_bases_collection_name_key'), 'knowledge_bases', ['collection_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_collection_id'), table_name='assets')
    op.drop_column('assets', 'collection_id')
    op.drop_column('assets', 'content')
    op.drop_column('assets', 'title')
    op.drop_column('assets', 'file_path')
    op.drop_index(op.f('ix_collections_workspace_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_boards_user_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_title'), table_name='boards')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
