"""add_positions

Revision ID: ed6dad71c9e5
Revises: ae5bd4d47dcf
Create Date: 2025-09-27 14:53:24.333435

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed6dad71c9e5'
down_revision = 'ae5bd4d47dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first, then set them to NOT NULL
    op.add_column('assets', sa.Column('position_x', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('assets', sa.Column('position_y', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('collections', sa.Column('position_x', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('collections', sa.Column('position_y', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('knowledge_bases', sa.Column('position_x', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('knowledge_bases', sa.Column('position_y', sa.Integer(), nullable=True, server_default='0'))
    
    # Update existing records to have position 0,0 if they are NULL
    op.execute("UPDATE assets SET position_x = 0 WHERE position_x IS NULL")
    op.execute("UPDATE assets SET position_y = 0 WHERE position_y IS NULL")
    op.execute("UPDATE collections SET position_x = 0 WHERE position_x IS NULL")
    op.execute("UPDATE collections SET position_y = 0 WHERE position_y IS NULL")
    op.execute("UPDATE knowledge_bases SET position_x = 0 WHERE position_x IS NULL")
    op.execute("UPDATE knowledge_bases SET position_y = 0 WHERE position_y IS NULL")
    
    # Now make the columns NOT NULL and remove server defaults
    op.alter_column('assets', 'position_x', nullable=False, server_default=None)
    op.alter_column('assets', 'position_y', nullable=False, server_default=None)
    op.alter_column('collections', 'position_x', nullable=False, server_default=None)
    op.alter_column('collections', 'position_y', nullable=False, server_default=None)
    op.alter_column('knowledge_bases', 'position_x', nullable=False, server_default=None)
    op.alter_column('knowledge_bases', 'position_y', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'position_y')
    op.drop_column('knowledge_bases', 'position_x')
    op.drop_column('collections', 'position_y')
    op.drop_column('collections', 'position_x')
    op.drop_column('assets', 'position_y')
    op.drop_column('assets', 'position_x')
    # ### end Alembic commands ###
