name: Deploy to GCE VM

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCE_SSH_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          GCE_KNOWN_HOSTS: ${{ secrets.GCE_KNOWN_HOSTS }}

      - name: Debug SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no slay-canvas-deploy@${{ secrets.GCE_VM_IP }} whoami
        continue-on-error: true

      - name: Deploy to GCE
        run: |
          ssh -o StrictHostKeyChecking=no slay-canvas-deploy@${{ secrets.GCE_VM_IP }} << 'EOF'
            set -x
            cd /home/kjmannn17/slay_canvas
            sudo git fetch origin main
            sudo git reset --hard origin/main
            /home/kjmannn17/slay_canvas/.venv/bin/pip install -r requirements.txt
            sudo systemctl restart slay_canvas
          EOF
